spring.application.name=intellilearn
server.port=8111
# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/intellilearn
spring.datasource.username=root
spring.datasource.password=root

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

file.upload-dir=uploads
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash-lite:generateContent